### PR TITLE
clean

### PR DESCRIPTION
**Pull request by azzra**

### CODE REVIEW

**Comment by azzra** [comment]
@tmartinfr wdyt? lgtd asap

**Review by tmartinfr — CHANGES_REQUESTED** [review]
@azzra Sorry i don't understand your two first acronym

**Comment by azzra** [comment]
wdyt stand for What Do you Think
lgtd stand for Let's Get This Done

**Review by tmartinfr — APPROVED** [review]
Fu***** Acronym Hipster

**Comment by tmartinfr** [comment]
FAH

**Pull request merged**
